version: "3.7"

services:
  celery_broker:
    image: rabbitmq:3.7.14-management
    ports:
      - "15672:15672"
    networks:
      - fenix
    deploy:
      mode: replicated
      replicas: 1
  celery_backend:
    image: redis:5.0.4
    networks:
      - fenix
    deploy:
      mode: replicated
      replicas: 1
  redis_database:
    image: redis:5.0.4
    networks:
      - fenix
    deploy:
      mode: replicated
      replicas: 1
  async_worker:
    build: 
      context: .
      dockerfile: Dockerfile.async_executor
    environment:
      - CELERY_BROKER_URI=amqp://celery_broker:5672
      - CELERY_BACKEND_URI=redis://celery_backend:6379
      - REDIS_DB_URI=redis://redis_database:6379
    command: ["celery", "worker", "-A", "async_executor.main", "-l", "info"]
    networks:
      - fenix
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - celery_backend
      - celery_broker
  async_executor:
    build:
      context: .
      dockerfile: Dockerfile.async_executor
    environment:
      - FLASK_APP=async_executor.main
      - CELERY_BROKER_URI=amqp://celery_broker:5672
      - CELERY_BACKEND_URI=redis://celery_backend:6379
      - REDIS_DB_URI=redis://redis_database:6379
    command: ["flask", "run", "--host=0.0.0.0"]
    ports:
      - "5001:5000"
    networks:
      - fenix
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - celery_backend
      - celery_broker
      - async_worker
      - redis_database

networks:
  fenix:
    driver: overlay
